const test = require('node:test');
const assert = require('node:assert/strict');
const { execFile } = require('node:child_process');
const { existsSync, readFileSync } = require('node:fs');
const { chmod, mkdir, mkdtemp, rm, stat, writeFile } = require('node:fs/promises');
const { tmpdir } = require('node:os');
const { dirname, join, resolve } = require('node:path');
const { promisify } = require('node:util');

const ROOT = resolve(__dirname, '..');
const README_PATH = resolve(ROOT, 'README.md');
const readme = readFileSync(README_PATH, 'utf8');
const execFileAsync = promisify(execFile);
const PREFIX_SETUP = 'mkdir -p "$HOME/.scmd-npx"';
const PREFIX_MODE = 'chmod 700 "$HOME/.scmd-npx"';
const ISOLATED_COMMAND = 'npx -y --prefix="$HOME/.scmd-npx" --prefer-online @nelsonjohnsolo/scmd@latest';
const SHORT_COMMAND = 'npx -y @nelsonjohnsolo/scmd';

function position(text) {
  const index = readme.indexOf(text);
  assert.notEqual(index, -1, `README must contain ${JSON.stringify(text)}`);
  return index;
}

test('README leads with one-line utility copy and the plugin launch path', () => {
  const lines = readme.split('\n');
  assert.match(lines[0], /^# SCMD\b/);
  assert.match(lines[2], /^SCMD reviews Claude Code's persistent memories /);
  assert.ok(lines[2].length <= 160, 'description should remain one concise line');

  const requirements = position('## Requirements');
  const node = position('Node.js 18');
  const npm = position('npm');
  const npx = position('npx');
  const add = position('/plugin marketplace add nelsonjohnsolo/scmd');
  const install = position('/plugin install scmd@scmd');
  const launch = readme.indexOf('/scmd:run', install);
  assert.notEqual(launch, -1, 'README must show /scmd:run after plugin installation');
  const prefixSetup = position(PREFIX_SETUP);
  const prefixMode = position(PREFIX_MODE);
  const isolated = position(ISOLATED_COMMAND);
  const shorthand = position(SHORT_COMMAND);
  assert.ok(requirements < node && node < add);
  assert.ok(npm < add && npx < add);
  assert.ok(add < install && install < launch && launch < prefixSetup && prefixSetup < prefixMode && prefixMode < isolated && isolated < shorthand);
  assert.match(readme.slice(requirements, add), /Windows.*Git Bash.*\/scmd:run.*shell snippets/is);
});

test('README recommends an isolated fresh release and warns about the shorthand', () => {
  const terminal = position('### Direct from a terminal');
  const isolated = position(ISOLATED_COMMAND);
  const shorthand = position(SHORT_COMMAND);
  assert.match(readme.slice(terminal, isolated), /recommend/i);
  assert.match(readme.slice(isolated, shorthand + SHORT_COMMAND.length + 300), /trusted director/i);
  assert.match(readme.slice(shorthand, shorthand + SHORT_COMMAND.length + 300), /npm.*project-local package/is);
  assert.doesNotMatch(readme, /--prefix="\$HOME\/\.scmd"/);
});

test('README has a non-broken demo placeholder and names every read/write boundary', () => {
  assert.match(readme, /^> Demo GIF: coming soon\.$/m);
  assert.match(readme, /~\/\.claude\/projects\/\*\/memory\/\*\.md/);
  assert.match(readme, /default.*~\/\.claude\/projects/is);
  assert.match(readme, /--root <dir>/);
  assert.match(readme, /CLAUDE_CONFIG_DIR/);
  assert.match(readme, /custom.*auto-memory root/is);
  assert.match(readme, /MEMORY\.md/);
  assert.match(readme, /session.*\.jsonl/is);
  assert.match(readme, /CLAUDE\.md/);
  assert.match(readme, /~\/\.scmd\/reviewed\.json/);
  assert.match(readme, /~\/\.scmd\/trash\//);
  assert.match(readme, /restore.*writes.*memory.*MEMORY\.md/is);
  assert.match(readme, /purge.*permanently deletes.*selected trash run/is);
  assert.match(readme, /only after you confirm|only when you apply/i);
});

test('README states the local privacy boundary before ending with Why', () => {
  const privacy = position('## Privacy');
  const why = position('## Why');
  assert.ok(privacy < why);
  assert.match(readme.slice(privacy, why), /127\.0\.0\.1/);
  assert.match(readme.slice(privacy, why), /every API request.*token/is);
  assert.doesNotMatch(readme.slice(privacy, why), /protects every request/i);
  assert.match(readme.slice(privacy, why), /no telemetry/i);
  assert.match(readme.slice(privacy, why), /rewrite text.*local Claude Code CLI.*account/is);
  assert.equal(readme.includes('!'), false, 'product copy should not use exclamation marks');
  assert.doesNotMatch(readme, /\b(?:Codex|employer|handoff|generated by AI|AI-generated code)\b/i);
  assert.match(readme.slice(why), /AI.*calling him [“"]daddy[”"].*start of every reply/is);
  assert.match(readme.slice(why), /wife saw it/is);
  assert.match(readme.slice(why), /did not know why/is);
  assert.match(readme.slice(why), /in (?:Claude Code )?memory/is);
  assert.match(readme.slice(why), /persistent memor/is);
});

test('README local links resolve to files and never point at a missing GIF', () => {
  const links = [...readme.matchAll(/!?\[[^\]]*\]\(([^)]+)\)/g)];
  for (const [, rawTarget] of links) {
    const target = rawTarget.trim().replace(/^<|>$/g, '').split('#')[0];
    if (!target || /^(?:https?:|mailto:)/i.test(target)) continue;
    const resolved = resolve(dirname(README_PATH), decodeURIComponent(target));
    assert.ok(existsSync(resolved), `broken local README link: ${rawTarget}`);
  }
  assert.doesNotMatch(readme, /!\[[^\]]*\]\([^)]*\.gif(?:[)#]|$)/i);
});

test('documented setup makes the isolated prefix usable from a clean home', async (t) => {
  const sandbox = await mkdtemp(join(tmpdir(), 'scmd-readme-prefix-'));
  t.after(() => rm(sandbox, { recursive: true, force: true }));

  const home = join(sandbox, 'home');
  const packageDir = join(sandbox, 'package');
  const prefix = join(home, '.scmd-npx');
  await mkdir(home);
  await mkdir(packageDir);
  await writeFile(join(packageDir, 'package.json'), JSON.stringify({
    name: 'scmd-prefix-probe',
    version: '1.0.0',
    bin: { 'scmd-prefix-probe': 'cli.js' },
  }));
  await writeFile(join(packageDir, 'cli.js'), '#!/usr/bin/env node\nconsole.log("PREFIX_OK")\n');
  await chmod(join(packageDir, 'cli.js'), 0o755);

  assert.equal(existsSync(prefix), false);
  await mkdir(prefix, { recursive: true, mode: 0o700 });
  if (process.platform !== 'win32') {
    await chmod(prefix, 0o700);
    assert.equal((await stat(prefix)).mode & 0o077, 0, 'prefix must not grant group or other permissions');
  }
  const npxCommand = process.platform === 'win32' ? 'npx.cmd' : 'npx';
  const { stdout } = await execFileAsync(npxCommand, [
    '-y',
    `--prefix=${prefix}`,
    `--package=file:${packageDir}`,
    'scmd-prefix-probe',
  ], {
    cwd: sandbox,
    env: {
      ...process.env,
      HOME: home,
      NPM_CONFIG_AUDIT: 'false',
      NPM_CONFIG_CACHE: join(sandbox, 'cache'),
      NPM_CONFIG_FUND: 'false',
      NPM_CONFIG_UPDATE_NOTIFIER: 'false',
    },
    timeout: 20_000,
  });
  assert.match(stdout, /PREFIX_OK/);
});
